##################################################################
# Fichier “Makefile”
# make all: mettre a jour le tout
# make clean: enlever les version executable
################ #################################################
CFLAGS = -g -std=c99 -D _BSD_SOURCE
COMP = cc $(CFLAGS)
ALL = tp1

all: $(ALL)
clean:
	rm $(ALL)

tp1: tp1.c
	$(COMP) tp1.c -o tp1
