##################################################################
# Fichier “Makefile”
# make all: mettre a jour le tout
# make clean: enlever les version executable
################ #################################################
CFLAGS = -std=c99 -fopenmp
COMP = gcc $(CFLAGS)
ALL = labo2

all: $(ALL)
clean:
	rm $(ALL)

labo2: labo2.c
	$(COMP) labo2.c -o labo2
